; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = nanoatmega328new

[env]
framework = arduino
monitor_speed = 500000

; --- Arduino Uno Environment ---
[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new

; --- Optimization Flags ---
build_flags = 
    ; Force AVR fast assembly
    -D uECC_ASM=5
    
    ; Maximize math unrolling
    -D uECC_OPTIMIZATION_LEVEL=3
    
    ; GCC speed optimization
    -O3

    ; CURVE Selection
    -D SECP256=1

extra_scripts = post:generate_asm.py